ojs_journal_submission_me:
    path:     /submission/me
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:index" }

ojs_journal_submission_all:
    path:     /submission/all
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:index", all: true }

ojs_journal_submission_start:
  path:     /submission/start
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:start" }
ojs_journal_submission_new:
  path:     /submission/new
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:new" }
ojs_journal_submission_edit:
  path:     /submission/edit/{id}
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:edit" }
ojs_journal_submission_preview:
  path:     /submission/preview/{articleId}
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:preview" }

ojs_journal_submission_orcid:
  path:     /submission/orcid
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:getOrcidAuthor" }

ojs_journal_submission_cancel:
    path:     /submission/cancel/{id}
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:cancel"}

