ojs_journal_board_index:
    path:     /board/
    defaults: { _controller: "OjsJournalBundle:Board:index" }

ojs_journal_board_show:
    path:     /board/{id}/show
    defaults: { _controller: "OjsJournalBundle:Board:show" }

ojs_journal_board_new:
    path:     /board/new
    defaults: { _controller: "OjsJournalBundle:Board:new" }

ojs_journal_board_create:
    path:     /board/create
    defaults: { _controller: "OjsJournalBundle:Board:create" }
    methods:  POST

ojs_journal_board_edit:
    path:     /board/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Board:edit" }

ojs_journal_board_update:
    path:     /board/{id}/update
    defaults: { _controller: "OjsJournalBundle:Board:update" }
    methods: [PUT]

ojs_journal_board_delete:
    path:     /board/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Board:delete" }
    methods: [DELETE]

ojs_journal_board_member_add:
    path:  /board/{boardId}/member/add
    defaults: { _controller: "OjsJournalBundle:Board:addMember" }
    methods:  [POST, PUT]

ojs_journal_board_member_remove:
    path:  /board/{boardId}/member/{id}/remove
    defaults: { _controller: "OjsJournalBundle:Board:removeMember" }

ojs_journal_board_oto_generate:
    path:  /board/oto-generate
    defaults: { _controller: "OjsJournalBundle:Board:otoGenerate" }
