ojs_journal_citation_index:
    path:     /article/{articleId}/citation/
    defaults: { _controller: "OjsJournalBundle:Citation:index" }

ojs_journal_citation_show:
    path:     /article/{articleId}/citation/{id}/show
    defaults: { _controller: "OjsJournalBundle:Citation:show" }

ojs_journal_citation_new:
    path:     /article/{articleId}/citation/new
    defaults: { _controller: "OjsJournalBundle:Citation:new" }

ojs_journal_citation_create:
    path:     /article/{articleId}/citation/create
    defaults: { _controller: "OjsJournalBundle:Citation:create" }
    methods:  POST

ojs_journal_citation_edit:
    path:     /article/{articleId}/citation/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Citation:edit" }

ojs_journal_citation_update:
    path:     /article/{articleId}/citation/{id}/update
    defaults: { _controller: "OjsJournalBundle:Citation:update" }
    methods:  [PUT]

ojs_journal_citation_delete:
    path:     /article/{articleId}/citation/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Citation:delete" }
    methods:  [DELETE]
