ojs_journal_filemanager_index:
    path:     /file-manager
    defaults: { _controller: "OjsJournalBundle:JournalFile:index" }

ojs_journal_filemanager_new:
    path:     /file-manager/new
    defaults: { _controller: "OjsJournalBundle:JournalFile:new" }

ojs_journal_filemanager_create:
    path:     /file-manager/create
    defaults: { _controller: "OjsJournalBundle:JournalFile:create" }
    methods:  [POST]

ojs_journal_filemanager_show:
    path:     /file-manager/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalFile:show" }

ojs_journal_filemanager_edit:
    path:     /file-manager/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalFile:edit" }

ojs_journal_filemanager_update:
    path:     /file-manager/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalFile:update" }
    methods:  [PUT]

ojs_journal_filemanager_delete:
    path:     /file-manager/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalFile:delete" }
    methods:  [DELETE]
