ojs_journal_issue_file_index:
    path:     /issue/{issueId}/file/
    defaults: { _controller: "OjsJournalBundle:IssueFile:index" }

ojs_journal_issue_file_show:
    path:     /issue/{issueId}/file/{id}/show
    defaults: { _controller: "OjsJournalBundle:IssueFile:show" }

ojs_journal_issue_file_new:
    path:     /issue/{issueId}/file/new
    defaults: { _controller: "OjsJournalBundle:IssueFile:new" }

ojs_journal_issue_file_create:
    path:     /issue/{issueId}/file/create
    defaults: { _controller: "OjsJournalBundle:IssueFile:create" }
    methods:  POST

ojs_journal_issue_file_edit:
    path:     /issue/{issueId}/file/{id}/edit
    defaults: { _controller: "OjsJournalBundle:IssueFile:edit" }

ojs_journal_issue_file_update:
    path:     /issue/{issueId}/file/{id}/update
    defaults: { _controller: "OjsJournalBundle:IssueFile:update" }
    methods:  [POST, PUT]

ojs_journal_issue_file_delete:
    path:     /issue/{issueId}/file/{id}/delete
    defaults: { _controller: "OjsJournalBundle:IssueFile:delete" }
    methods:  [POST, DELETE]
