ojs_journal_index_index:
    path:     /index/
    defaults: { _controller: "OjsJournalBundle:JournalIndex:index", journal: 0 }
    requirements:
      journal: \d+

ojs_journal_index_show:
    path:     /index/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalIndex:show" }

ojs_journal_index_new:
    path:     /index/new/
    defaults: { _controller: "OjsJournalBundle:JournalIndex:new",journal: null }

ojs_journal_index_create:
    path:     /index/create/
    defaults: { _controller: "OjsJournalBundle:JournalIndex:create",journal: null }
    methods:  POST

ojs_journal_index_edit:
    path:     /index/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalIndex:edit" }

ojs_journal_index_update:
    path:     /index/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalIndex:update" }
    methods: [PUT]

ojs_journal_index_delete:
    path:     /index/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalIndex:delete" }
    methods: [DELETE]
