ojs_journal_page_index:
    path:     /page
    defaults: { _controller: "OjsJournalBundle:JournalPage:index" }

ojs_journal_page_new:
    path:     /page/new
    defaults: { _controller: "OjsJournalBundle:JournalPage:new" }

ojs_journal_page_create:
    path:     /page/create
    defaults: { _controller: "OjsJournalBundle:JournalPage:create" }
    methods:  [POST]

ojs_journal_page_show:
    path:     /page/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalPage:show" }

ojs_journal_page_edit:
    path:     /page/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalPage:edit" }

ojs_journal_page_update:
    path:     /page/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalPage:update" }
    methods:  [PUT]

ojs_journal_page_delete:
    path:     /page/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalPage:delete" }
    methods:  [DELETE]
