ojs_journal_settings_index:
    path:  /settings/
    defaults: { _controller: "OjsJournalBundle:Manager:journalSettings" }

ojs_journal_settings_update:
    path:  /settings/update
    defaults: { _controller: "OjsJournalBundle:Manager:updateJournal" }
    methods:  [PUT, POST]

ojs_journal_settings_submission:
    path:  /settings/submission
    defaults: { _controller: "OjsJournalBundle:Manager:journalSettingsSubmission" }
